PodDisruptionBudget:
  minAvailable: 50%
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - app-deploy
          topologyKey: kubernetes.io/hostname
        weight: 1
affinitySidekiq:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - app-deploySidekiq
          topologyKey: kubernetes.io/hostname
        weight: 1
annotations:
  prometheus.io/port: '3000'
  prometheus.io/scrape: 'true'
appExtConfig:
  DL_APP_NAME: ecommerceapp
  HOST_URL: cocomore-300779-ruby.b300779.dev.eastus.az.svc.builder.cafe/
  NAMESPACE: CocoMore-300779
  OFFICE365_ACCOUNT_ID: 4006c537-61a5-42bb-a9e6-6ff53b75730c
  OFFICE365_EMAIL: admin@builderautomddajpvvcli.onmicrosoft.com
  OFFICE365_PASSWORD: G4mDHtjP*
  OFFICE365_TENANT: 8dfbf481-d9c1-4e49-9745-845e9542e640
  PROJECT_TYPE: studio_store
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_MAX_THREADS: '10'
  REDIS_URL: redis
  RUBY_ANALYTICS_TOKEN: ADvoiejfyI6IHGJbitMe9MGLbkPRxj6n
  SMTP_ADDRESS: email-smtp.us-east-1.amazonaws.com
  SMTP_PORT: '587'
  USER_ID: edf0fffc-941d-461c-9d3f-0a0099af5e35
  USER_NAME: cocomore_300779@email.store.builder.ai
  SMTP_EMAIL_USERNAME: AKIA2YL6V6FWQO3Q434A
  SMTP_EMAIL_PASSWORD: BA+0A6h+EwUVWi6nTFA4bYrM2rceY9YABawqMhW/8GHL
autoscaling:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Percent
          value: 25
      stabilizationWindowSeconds: 600
    scaleUp:
      policies:
        - periodSeconds: 30
          type: Percent
          value: 100
      stabilizationWindowSeconds: 0
  enabled: true
  maxReplicas: 4
  minReplicas: 2
  targetCPU: 50
  targetMemory: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: registry.gitlab.builder.ai/template-app
  tag: 8.8.8
imagePullSecrets: []
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  enabled: true
  hosts:
    - host: rrapp.local
      paths:
        - /
  rsa_key_length: '2048'
  tls:
    - hosts:
        - rrapp.local
      secretName: https-cert
nameOverride: ''
nodeSelector: {}
podSecurityContext: {}
probes:
  livenessProbe:
    initialDelaySeconds: 40
    path: /healthcheck
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 40
    path: /healthcheck
    periodSeconds: 20
probesSidekiq:
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
railsMigration:
  command:
    - bundle
    - exec
    - rails
    - db:migrate
    - db:seed
  enabled: true
  retry: 2
  timeout: 300
railsSidekiq:
  annotations:
    prometheus.io/port: '9394'
    prometheus.io/scrape: 'true'
  autoscaling:
    behavior:
      scaleDown:
        policies:
          - periodSeconds: 60
            type: Percent
            value: 25
        stabilizationWindowSeconds: 600
      scaleUp:
        policies:
          - periodSeconds: 30
            type: Percent
            value: 100
        stabilizationWindowSeconds: 0
    enabled: true
    maxReplicas: 4
    minReplicas: 2
    targetCPU: 50
    targetMemory: 80
  enabled: false
  replicaCount: 1
replicaCount: 2
resources:
  limits:
    cpu: 350m
    memory: 515Mi
  requests:
    cpu: 350m
    memory: 315Mi
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
sidekiqResources:
  limits:
    cpu: 350m
    memory: 515Mi
  requests:
    cpu: 350m
    memory: 315Mi
tolerations: []
